apiVersion: v2
name: elasticsearch
version: 0.1.4
description: Extension of the stable/elasticsearch chart
home: https://github.com/onedata/charts/stable/elasticsearch
sources:
  - https://github.com/onedata/charts/stable/elasticsearch
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
appVersion: 6.6.0

dependencies:
- name: elasticsearch
  version: 7.17.3
  repository: "@elastic"

- name: onedata-chart-utils
  version: 0.2.16
  repository: file://../onedata-chart-utils
