# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  imageTag: "7.17.3"
  imagePullPolicy: "IfNotPresent"

  replicas: 1
  minimumMasterNodes: 1

  persistence:
    enabled: false
    annotations: {}

