apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ template "releaseName" . }}"
    heritage: "{{ .Release.Service }}"
    component: "couchbase"
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  type: "{{ .Values.serviceType }}"
  clusterIP: None
  ports:
    - name: couchbase-1
      port: 8091
    - name: couchbase-2
      port: 8092
    - name: couchbase-3
      port: 8093
    - name: couchbase-4 
      port: 8094
  selector:
    app: {{ template "fullname" . }}
