apiVersion: v2
name: oneprovider
version: 0.2.18
description: The main data management component of Onedata, deployed at each storage provider site, responsible for unifying and controlling access to data over low level storage resources of the provider.
keywords:
  - onedata
  - oneprovider
home: https://www.onedata.org
sources:
  - https://github.com/onedata/onedata
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
engine: gotpl
appVersion: 20.02.12

dependencies:
- name: oneclient
  version: 0.2.14
  repository: file://../oneclient
  condition: oneclient.enabled

- name: onedata-cli
  version: 0.2.15
  repository: file://../onedata-cli
  condition: onedata-cli.enabled

- name: onedata-chart-utils
  version: 0.2.14
  repository: file://../onedata-chart-utils

- name: volume-s3
  version: 0.2.10
  repository: file://../volume-s3
  condition: volume-s3.enabled

- name: volume-ceph
  version: 0.2.11
  repository: file://../volume-ceph
  condition: volume-ceph.enabled

- name: volume-nfs
  version: 0.2.13
  repository: file://../volume-nfs
  condition: volume-nfs.enabled

- name: volume-gluster
  version: 0.2.8
  repository: file://../volume-gluster
  condition: volume-gluster.enabled

- name: volume-swift
  version: 0.2.8
  repository: file://../volume-swift
  condition: volume-swift.enabled
  
- name: volume-webdav
  version: 0.2.2
  repository: file://../volume-webdav
  condition: volume-webdav.enabled
  
- name: volume-dcache
  version: 0.2.2
  repository: file://../volume-dcache
  condition: volume-dcache.enabled

- name: luma
  version: 0.2.8
  repository: file://../luma
  condition: luma.enabled
  
- name: jupyter-notebook
  version: 0.2.1
  repository: file://../jupyter-notebook
  condition: jupyter-notebook.enabled
  
- name: openfaas 
  version: 7.3.1
  repository:  file://../../../onedata/faas-netes/chart/openfaas
  condition: openfaas.enabled