apiVersion: v2
name: onezone
version: 0.2.18
description: Onezone is a Onedata service enabling federation of storage providers and user authentication.
keywords:
  - onedata
  - onezone
home: https://www.onedata.org
sources:
  - https://github.com/onedata/onezone
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
appVersion: 21.02.7

dependencies:
- name: onedata-chart-utils
  version: 0.2.16
  repository: file://../onedata-chart-utils

- name: keycloak
  version: 0.1.7
  repository: file://../keycloak
  condition: keycloak.enabled
  import-values:
    - child: init
      parent: keycloak-workaround.init

- name: elasticsearch
  version: 0.1.4
  repository: file://../elasticsearch
  condition: elasticsearch.enabled

- name: token-dispenser
  version: 0.1.6
  repository: file://../token-dispenser
  condition: token-dispenser.enabled

- name: handle-proxy-mock
  version: 0.1.1
  repository: file://../handle-proxy-mock
  condition: handle-proxy-mock.enabled

- name: pebble
  version: 1.2.0
  repository: https://jupyterhub.github.io/helm-chart
  condition: pebble.enabled