apiVersion: v2
name: onezone
version: 0.2.16
description: Onezone is a Onedata service enabling federation of storage providers and user authentication.
keywords:
  - onedata
  - onezone
home: https://www.onedata.org
sources:
  - https://github.com/onedata/onezone
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
engine: gotpl
appVersion: 20.02.12

dependencies:
- name: onedata-chart-utils
  version: 0.2.14
  repository: file://../onedata-chart-utils

- name: keycloak
  version: 0.1.5
  repository: file://../keycloak
  condition: keycloak.enabled
  import-values:
    - child: init
      parent: keycloak-workaround.init

- name: elasticsearch
  version: 0.1.1
  repository: file://../elasticsearch
  condition: elasticsearch.enabled

- name: token-dispenser
  version: 0.1.4
  repository: file://../token-dispenser
  condition: token-dispenser.enabled