dependencies:
- name: onedata-chart-utils
  version: 0.2.13
  repository: file://../onedata-chart-utils

- name: keycloak
  version: 0.1.4
  repository: file://../keycloak
  condition: keycloak.enabled
  
- name: elasticsearch
  version: 0.1.0
  repository: file://../elasticsearch
  condition: elasticsearch.enabled
  
- name: token-dispenser
  version: 0.1.3
  repository: file://../token-dispenser
  condition: token-dispenser.enabled