{{- if .Values.users }}

{{- $keycloak_realmId := "UNINITIALIZED" }}
{{- if hasKey (index $.Values "keycloakInstance" ) "init" }}
{{- $keycloak_realmId := $.Values.keycloakInstance.init.realmId }}
{{- end }}
---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-users
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ template "releaseName" . }}"
    heritage: "{{ .Release.Service }}"
    job: {{ template "fullname" . }}-users
    component: {{ .Chart.Name }}-users
    dependency-level: "5"
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{ template "releaseName" . }}"
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}"
        release: "{{ template "releaseName" . }}"
        heritage: "{{ .Release.Service }}"
        job: {{ template "fullname" . }}-users
        component: {{ .Chart.Name }}-users
        dependency-level: "4"
      annotations:
        version: "{{ .Chart.Version }}"
    spec:
      hostNetwork: {{ template "hostNetwork" . }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if (index .Values "wait_for_release" "enabled") }}
      initContainers:
        - name: wait-for-release
          image: {{ .Values.wait_for.image }}
          imagePullPolicy: {{ template "imagePullPolicy" dict "root" . "context" .Values.wait_for }}
          args:
            - "pod"
            - >
              -l release in ({{ template "releaseName" . }}), chart notin ({{ .Chart.Name }}, oneclient, jupyter-notebook)
      {{- end }}
{{ include "imagePullSecrets" . | indent 6 }}
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ template "imagePullPolicy" dict "root" . }}
        env:
          - name: ONEZONE_HOST
            value: "https://{{ template "onezone_name" . }}"
          - name: ONEZONE_API_KEY
            value: "supplied_at_runtime"
          - name: ONEPANEL_BASIC_AUTH
            value: "{{ template "onepanel_emergency_username_template" . }}:{{ template "onepanel_emergency_password_template" . }}"
          - name: ONEPROVIDER_HOST
            value: "https://{{ template "oneprovider_name" . }}"
          - name: ONEPANEL_HOST
            value: "https://{{ template "onezone_name" . }}:9443"
          - name: KEYCLOAK_HOST
            value: "http://{{ template "keycloak_service_url" . }}"
          - name: TERM # otherwise zsh and bash autocompletion used in this container tends to go crazy
            value: "xterm-256color"
        command:
          - "bash"
          - "-c"
          - >
            set -e;
            echo "-k" > ~/.curlrc ; echo "-f" >> ~/.curlrc ;
            export KEYCLOAK_VARS_INITIALIZED="False" ;
        {{- range .Values.users }}{{ if (hasKey . "idps"  )}}
        {{ if (hasKey .idps "onepanel" )}}{{ if (hasKey .idps.onepanel "mode" )}}{{ if and .idps.onepanel.enabled (eq .idps.onepanel.mode "rest") }}
            printf "Creating user {{ .name }} [response: " ;
            curl --silent -k -u ${ONEPANEL_BASIC_AUTH} -X POST -H "Content-type: application/json" -d '{"username": "{{ .name }}", "password": "{{ .password }}"}' ${ONEZONE_HOST}/api/v3/onezone/users ;
            echo "] Success." ;
        {{- end }}{{- end }}{{- end }}
        {{- if (hasKey .idps "keycloak" )}}{{ if (hasKey .idps.keycloak "mode" )}}{{ if and .idps.keycloak.enabled (eq .idps.keycloak.mode "duringCrossSupportJob") }}
            if [[ ${KEYCLOAK_VARS_INITIALIZED} == "False" ]] ; then
              realmId={{ template "keycloak_realmId_template" $ }} ;
              keycloak_url=${KEYCLOAK_HOST} ;
              export KEYCLOAK_TOKEN={{ template "onedata-chart-utils.createKeycloakToken" $ }} ;
              KEYCLOAK_VARS_INITIALIZED="True" ;
            fi ;
        {{ template "onedata-chart-utils.createKeycloakUser" dict "user" . }}
        {{- end }}{{- end }}{{- end }}
        {{- end }}{{- end }}
            exit 0;
{{- end }}
