apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" . }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      chart: {{ .Chart.Name }}
      release: {{ template "releaseName" . }}
      heritage: {{ .Release.Service }}
      component: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ .Chart.Name }}
        release: {{ template "releaseName" . }}
        heritage: {{ .Release.Service }}
        component: {{ .Chart.Name }}
      annotations:
        version: "{{ .Chart.Version }}"
    spec:
      hostname: {{ .Chart.Name | quote }}
      subdomain: {{ template "fullname" . }}
      hostNetwork: {{ template "hostNetwork" . }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
{{ include "imagePullSecrets" . | indent 6 }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ template "imagePullPolicy" dict "root" . }}
        ports:
          - containerPort: 80
          - containerPort: 5000
          - containerPort: 6800
          - containerPort: 6801
          - containerPort: 6802
          - containerPort: 6803
          - containerPort: 6804
          - containerPort: 6805
        env:
        - name: MON_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CEPH_DEMO_SECRET_KEY
          value: "cNmUrqpBKjCMzcfqG8fg4Qk07Xkoyau52OmvnSsz"
        - name: CEPH_DEMO_ACCESS_KEY
          value: "G1EZ5R4K6IJ7XUQKMAED"
        - name: CEPH_DEMO_UID
          value: "{{ .Values.username }}"
        command:
          - "/bin/bash"
          - "-c"
          - >
            a=$(ip -o -f inet addr show | awk '/scope global/{sub(/[^.]+\//,"0/",$4);print $4}') ;
            export CEPH_PUBLIC_NETWORK="${a%.*}.0/24" ;
            export CEPH_NETWORK=$CEPH_PUBLIC_NETWORK ;
            env ;
            /entrypoint.sh demo;
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - >
                  wget -t 2 --spider --connect-timeout 2 $MON_IP:6789 ;
                  while [[ $? -ne 0 ]] ; do
                    sleep 2 ;
                    echo "Waiting for ceph server to start to create pools" ;
                    wget -t 2 --spider --connect-timeout 2 $MON_IP:6789 ;
                  done ;
                  while [[ ! -f /etc/ceph/I_AM_A_DEMO ]] ; do
                    sleep 2 ;
                  done ;
                  ceph osd pool create {{ .Values.pool_name }} 8 ;
                  {{- /* Solves 'ceph health' error regarding unassinged aplication */ -}}
                  ceph rbd pool init {{ .Values.pool_name }} ;
                  ceph osd pool application enable {{ .Values.pool_name }} cephfs --yes-i-really-mean-it ;
                  ceph osd pool application enable {{ .Values.pool_name }} rbd --yes-i-really-mean-it ;
                  ceph osd pool application enable {{ .Values.pool_name }} rgw --yes-i-really-mean-it ;
                  echo '[{{ .Values.username }}]' > /etc/ceph/ceph.{{ .Values.username }}.keyring ;
                  echo '        key = {{ .Values.key }}' >> /etc/ceph/ceph.{{ .Values.username }}.keyring ;
                  echo '        caps mon = "allow r"' >> /etc/ceph/ceph.{{ .Values.username }}.keyring ;
                  echo '        caps osd = "allow rwx pool={{ .Values.pool_name }}"' >> /etc/ceph/ceph.{{ .Values.username }}.keyring ;
                  ceph auth import -i /etc/ceph/ceph.{{ .Values.username }}.keyring ;
                  {{- /*
                  # Not sure if all options here are needed to nesure 'ceph health' command to return OK status
                  # Set ceph config to be more willing to run in poor k8s cluster
                  # to get all options run: ceph config show-with-defaults mds.volume-ceph
                  # ceph config show mon.volume-ceph %}}
                  # Create test pool and a test user */ -}}
                  ceph config set mon.volume-ceph mon_data_avail_warn 1;
                  ceph config set mon.volume-ceph mon_data_avail_crit 1;
                  ceph config set mon.volume-ceph mon_pg_warn_min_per_osd 10;
                  ceph config set osd.0 mon_data_avail_warn 1;
                  ceph config set osd.0 mon_data_avail_crit 1;
                  ceph config set osd.0 mon_pg_warn_min_per_osd 10;
        # https://github.com/ceph/ceph-container/blob/master/examples/kubernetes/ceph-mon-v1-dp.yaml
        livenessProbe:
          tcpSocket:
            port: 6789