apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" . }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
  annotations:
  {{- if .Values.deployAsPreInstallHook }}
    "helm.sh/hook": pre-install
  {{- end }}
    version: "{{ .Chart.Version }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: nfs-tcp
      port: 2049
      protocol: TCP
    - name: nfs-udp
      port: 2049
      protocol: UDP
    - name: mountd
      port: 20048
    - name: rpcbind-tcp
      port: 111
      protocol: TCP
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: {{ template "fullname" . }}
