apiVersion: v2
name: cross-support-job-3p
version: 0.2.18
description: Chart that populates deployment environment created with onedata/onedata-3p chart with spaces
keywords:
  - onedata
  - initialization
  - spaces
home: https://github.com/onedata/charts
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
appVersion: 21.02.7

dependencies:
- name: onedata-chart-utils
  version: 0.2.15
  repository: file://../onedata-chart-utils

- name: onedata-3p
  version: 0.2.16
  repository: file://../onedata-3p
  condition: onedata-3p.enabled
  import-values:
    - child: onezone.onepanel_emergency_account
      parent: global.onepanelEmergencyAccount
    - child: onezone.main_onezone_admin
      parent: global.onezoneMainAdmin
    - child: onezone.keycloak-workaround
      parent: global.keycloakInstance