dependencies:
- name: onedata-chart-utils
  version: 0.2.11
  repository: https://onedata.github.io/charts/

- name: onedata-3p
  version: 0.2.13
  repository: https://onedata.github.io/charts/
  condition: onedata-3p.enabled  
  import-values:
    - child: onezone.onepanel_emergency_account
      parent: global.onepanelEmergencyAccount
    - child: onezone.main_onezone_admin
      parent: global.onezoneMainAdmin
    - child: onezone.keycloak
      parent: global.keycloakInstance