dependencies:
  - name: onedata-chart-utils
    version: 0.2.14
    repository: https://onedata.github.io/charts/
  - name: cluster-manager
    version: 0.1.0
    repository: file://../cluster-manager