apiVersion: v2
name: token-dispenser
version: 0.1.5
description: Proxy for requesting Onezone API tokens
keywords:
  - token
  - proxy
home: https://github.com/onedata/token-dispenser
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
appVersion: 0.1.0

dependencies:
- name: onedata-chart-utils
  version: 0.2.15
  repository: file://../onedata-chart-utils