# Default values for token-dispenser
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: onedata/token-dispenser:54a9538
imagePullPolicy: IfNotPresent
serviceType: ClusterIP

# A simple config that:
# for onepanel you just provide type
# for keycloak you provider type, name and prefix
# the top keys in the config are not taken into account
# only type is important
config:
  onepanel: 
    type: onepanel
  keycloak-rhea:
    name: rhea
    tokenPrefix: onedata
    type: keycloak

# The generalization of nodeSelector.
# Allows for more fine grained controls over which
# nodes are selected by a kubernetes scheduler
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# List of taints which are tolerated by the pods 
# when nodes are selected by a kubernetes scheduler
# https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}

# Specify a map of key-value pairs. For the pod 
# to be eligible to run on a node, the node 
# must have each of the indicated key-value pairs as labels
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}