{{- if (index .Values "volume-nfs" "enabled") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-nfs-pvc
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" . }}
    heritage: {{ .Release.Service }}
    component: "oneprovider"
    type: nfs
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ index .Values "volume-nfs" "storage_claim" }}
  selector: 
    matchLabels:
      type: nfs
      owner: {{ .Values.suffix }}
{{- end }}
