{{- if (index .Values "generate-certificates" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secret-tls
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ template "releaseName" . }}"
    heritage: "{{ .Release.Service }}"
    component: "oneprovider"
  annotations:
    version: "{{ .Chart.Version }}"
data:
  tls.key: ""
  tls.crt: ""
  k8s.crt: ""
{{- end }}